/* prettier-ignore */
export type ControlListServices =
  | 'levers'
  | 'contracts'
  | 'institutions'
  | 'userStaff'
  | 'countries'
  | 'languages'
  | 'capSharingFormats'
  | 'capSharingTypes'
  | 'capSharingDegrees'
  | 'capSharingLengths'
  | 'capSharingGenders'
  | 'capSharingDeliveryModalities'
  | 'capSharingSessionPurpose'
  | 'yesOrNo'
  | 'policyTypes'
  | 'policyStages'
  | 'geoFocus'
  | 'regions'
  | 'geoScopeOpenSearch'
  | 'openSearchCountries'
  | 'openSearchResult'
  | 'innoDevOutput'
  | 'innoUseOutput'
  | 'openSearchSubNationals'
  | '';
